### ISSUE TITLE
Inconsistent use of syntactic sugar

### ISSUE THREAD

**Issue by jjatria** [sanko/SDL2.pm#1]
I came across this project while working on my own bindings for SDL2 using FFI, and since yours are further along, I thought I'd try to contribute to yours instead.

One thing I noticed is that, while the bindings are pretty much a direct sugar-free representation of the SDL2 API, there are some functions that do not behave like documented in the the SDL2 docs.

Take, for example, `SDL_GetRendererInfo`:

```
# Using SDL2::FFI
my $info = SDL_GetRendererInfo($renderer)
    or die 'Could not get renderer info: ' . SDL_GetError;

# As documented in SDL2
my $info = SDL2::RendererInfo->new;
SDL_GetRendererInfo($renderer, $info)
    and die 'Could not get rendrer info: ' . SDL_GetError;
```

(Other examples include `SDL_RenerDrawPoints` and friends, which in SDL2::FFI figure out the number of elements in the list automatically.)

There is little question in my mind that the first is much more Perlish. But I fear that adding _a little_ syntactic sugar would make bindings like this _harder_ to use, because now you have to remember that _most_ places have no sugar and behave like in C, but _some_ of them have been Perlified.

I think we definitely would eventually want some Perlish wrapper around SDL2 (similar to what was attempted in the SDLx namespace), but I wonder if it would be simpler to keep SDL2::FFI as a sugar-free implementation of the SDL2 API (which would mean it would be simpler to document and understand for users familiar with SDL2), and work on how to make it feel at home in Perl once we know the bindings work.

**Comment by sanko** [comment]
Yeah, incomplete projects tend to be incomplete.

**Comment by jjatria** [comment]
I did not mean any disrespect. I only wrote because I wanted to contribute to your project, and I was wondering what was the direction you had in mind for it.

There's already a couple of us who are working independently on the same thing, and I thought it would be wiser to pool our resources, but it seems like you are keen on working on this on your own. Best of luck if that's the case.
